CREATE TABLE IF NOT EXISTS resumes (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  file_name VARCHAR(255) NOT NULL,
  uploaded_at TIMESTAMPTZ DEFAULT now(),
  name VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(50),
  linkedin_url VARCHAR(255),
  portfolio_url VARCHAR(255),
  summary TEXT,
  work_experience JSONB,
  education JSONB,
  technical_skills JSONB,
  soft_skills JSONB,
  projects JSONB,
  certifications JSONB,
  resume_rating INTEGER,
  improvement_areas TEXT,
  upskill_suggestions JSONB
);
